# Generated by Django 5.2 on 2025-04-28 08:35

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "username",
                    models.CharField(max_length=32, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "name",
                    models.CharField(db_index=True, max_length=32, verbose_name="昵称"),
                ),
                (
                    "email",
                    models.CharField(db_index=True, max_length=64, verbose_name="邮箱"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="手机号码"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(default="", max_length=128, verbose_name="头像"),
                ),
                (
                    "created_name",
                    models.CharField(max_length=32, verbose_name="创建人姓名"),
                ),
                (
                    "updated_name",
                    models.CharField(
                        default="", max_length=32, verbose_name="上次修改人姓名"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(null=True, verbose_name="上次登陆时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "is_super",
                    models.BooleanField(default=False, verbose_name="是否是管理员"),
                ),
                (
                    "created",
                    apps.core.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_user_created",
                        to="user.platformuser",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated",
                    apps.core.models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_user_updated",
                        to="user.platformuser",
                        verbose_name="上次修改人",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
